version: '2'

services:
    web:
        build: .
        links:
            - couchdb:couchdb
            - redis:redis
        ports:
            - "3000:3000"
        restart: "always"
        depends_on:
            - couchdb
            - redis

    # webdev:
    #     build: ./dev
    #     links:
    #         - couchdb:couchdb
    #         - redis:redis
    #     ports:
    #         - "3000:3000"
    #     restart: "always"
    #     volumes:
    #         - /d/SCWamp/Docs/aphclubuk/:/app/
    couchdb:
        image: klaemo/couchdb:1.6.1
        expose:
            - "5948"
        volumes:
            - /home/admin/web/aphclubuk/models/data/couchdb:/usr/local/var/lib/couchdb
        restart: "always"
    redis:
        image: redis:latest
        expose:
            - "6379"
        restart: "always"
